sonnuage/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('playlists', 'PlaylistController');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/* Ajout de louis */
Route::get('playlists', 'PlaylistController@index')->name('playlists');

Route::get('show', 'PlaylistController@show')->name('show');

Route::get('modify', 'UserController@modify_view');

Route::post('profile', 'UserController@update_avatar');

Route::get('/admin', 'AdminController@index')->name('homeAdmin');

Route::resource('search', 'SearchController');

Route::get('/search', 'SearchController@index')->name('search');

Route::post('/search', 'SearchController@search')->name('search');

Route::resource('upload', 'UploadController');
//Route::get('/upload', 'UploadController@uploadForm')->name('upload');
//
//Route::post('/upload', 'UploadController@uploadSubmit')->name('upload');



/* Ajout de Antoine */
Route::resource('albums', 'AlbumController');

Route::get('albums', 'AlbumController@index')->name('albums');

Route::get('show', 'AlbumController@show')->name('show');

Route::resource('artists', 'ArtistController');

Route::get('artists', 'ArtistController@index')->name('artists');

Route::get('show', 'ArtistController@show')->name('show');

Route::resource('musics', 'MusicController');

Route::get('musics', 'MusicController@index')->name('musics');

Route::get('show', 'MusicController@show')->name('show');

Route::post('destroy', 'MusicController@delete')->name('delete');

sonnuage/app/Album.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Album extends Model
{
    protected $fillable = [
        'title', 'artist_id', 'release_date'
    ];

    public function set_release_date_attribute($date)
    {
        $this->attributes['release_date'] = Carbon::parse($date);
    }

    public function musics(){
        return $this->hasMany('App\Music');
    }

    public function artists(){
        return $this->belongsTo('App\Artist');
    }
}

sonnuage/app/Http/Controllers/AlbumController.php
<?php

namespace App\Http\Controllers;

use App\Album;
use App\Music;
use App\Artist;
use Illuminate\Http\Request;

class AlbumController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $albums = Album::all();

        return view('albums.index', compact('albums'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $artists = Artist::all();
        $musics = Music::all();
        return view('albums.create', compact('artists'), compact('musics'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'artist_id' => 'required',
            'title' => 'required',
            'release_date' => 'required',
            'music_id' => 'required',
        ]);

        Album::create($request->all());

        return redirect()->route('albums')
            ->with('success', 'Album created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Album  $album
     * @return \Illuminate\Http\Response
     */
    //public function show(Album $album)

    public function show(Album $album)
    {
        return view('albums.show', compact('album'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Album  $album
     * @return \Illuminate\Http\Response
     */
    public function edit(Album $album)
    {
        return view('albums.edit', compact('album'));
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Album  $album
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Album $album)
    {
        $request->validate([
            'artist_id' => 'required',
            'title' => 'required',
            'release_date' => 'required',
            'music_id' => 'required',
        ]);

        $album->update($request->all());

        return redirect()->route('albums')
            ->with('success', 'Album updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Album  $album
     * @return \Illuminate\Http\Response
     */
    public function destroy(Album $album)
    {
        $album->delete();

        return redirect()->route('albums')
            ->with('success', 'albums deleted successfully');
    }
}

sonnuage/resources/views/albums/create.blade.php
@extends('layout')

@section('content')

<div class="container mt-4">
    <div class="col-lg-12 margin-tb d-flex justify-content-between mb-2">
        <div class="pull-left">
            <h2>Ajoutez un nouvel album</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('albums') }}"> Retour</a>
        </div>
    </div>

    @if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <form action="{{ route('albums.store') }}" method="POST">
        @csrf

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Title:</strong>
                    <input type="text" name="title" class="form-control" placeholder="Title">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Artiste :</strong>

                    <select name="artist_id" id="artist">
                        @foreach($artists as $artist)
                        <option value="{{ $artist->id }}">{{ $artist->name }}</option>
                        @endforeach
                    </select>
                    <!-- <textarea class="form-control" name="artist_id" placeholder="Artist_id"></textarea> -->
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>music_id</strong>
                    <textarea class="form-control" name="music_id" placeholder="Music_id"></textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Date de sortie</strong>
                    <input type="date" class="form-control" name="release_date" placeholder="Release_date">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
</div>

@endsection

sonnuage/resources/views/albums/edit.blade.php
@extends('layout')

@section('content')

<div class="container mt-4">
    <div class="col-lg-12 margin-tb d-flex justify-content-between mb-2">
        <div class="pull-left">
            <h2>Modifiez l'album</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('albums') }}">Retour</a>
        </div>
    </div>
    @if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif
    <form action="{{ route('albums.update',$album->id) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="container">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Titre:</strong>
                    <input type="text" name="title" value="{{ $album->title }}" class="form-control" placeholder="Title">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Date de sortie:</strong>
                    <input type="date" name="release_date" value="{{ $album->release_date }}" class="form-control" placeholder="Release_date">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Artist id:</strong>
                    <input type="text" name="artist_id" value="{{ $album->artist_id }}" class="form-control" placeholder="Artist_id">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Music id:</strong>
                    <input type="text" name="music_id" value="{{ $album->music_id }}" class="form-control" placeholder="music_id">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
</div>

@endsection

sonnuage/resources/views/albums/index.blade.php
@extends('layout')

@section('content')
<div class="container">
    <div class="col-lg-12 margin-tb d-flex justify-content-between mb-2">
        <div class="pull-left">
            <h2>Tout vos Albums</h2>
        </div>
    </div>

    <div class="group-playlists">
        @foreach(App\Album::select(['albums.id', 'albums.title', 'albums.artist_id', 'albums.release_date', 'artists.pseudo', 'musics.cover'])
        ->leftJoin('artists', 'albums.artist_id', '=', 'artists.id')
        ->leftJoin('musics', 'albums.id', '=', 'musics.album_id')
        ->get() as $album)
        <div class="playlist-unit">
            <a href="{{ route('albums.show',$album->id) }}">
                <img src="/storage/covers/{{  $album['pseudo'] }}/{{ $album['cover'] }}" alt="album" />
                <h3>{{ $album['title'] }}</h3>
                <p>{{ $album['artist_id'] }}</p>
                <p>{{  date_format(date_create($album['release_date']), 'Y') }}</p>
            </a>
        </div>
        @endforeach
    </div>
</div>
@endsection

sonnuage/resources/views/albums/show.blade.php
@extends('layout')

@section('content')
    <?php
    $artist = App\Music::select('artists.pseudo', 'musics.cover')
        ->leftJoin('artists', 'musics.artist_id', '=', 'artists.id')
        ->where([
            ['artist_id', '=', $album->artist_id],
            ['album_id', '=', $album->id],
        ])
        ->first();
    ?>
<div id="album">
    <div class="col-lg-12 margin-tb d-flex justify-content-between mb-2">
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('albums') }}">Retour</a>
        </div>
    </div>
    <div id="baniere">
        <div class="cover">
            <img src="/storage/covers/{{ $artist->pseudo }}/{{ $artist->cover }}" alt="{{ $album->title }}_cover" />
        </div>
        <div id="text">
            <h2>{{ $album->title }}</h2>
            <p>{{ $artist->pseudo }}</p>
            <p>{{ date_format(date_create($album->release_date), 'Y') }}</p>
        </div>
    </div>
    <div id="music-list">
        <ul>
            @foreach (App\Music::select('musics.name', 'artists.pseudo')
            ->leftJoin('artists', 'musics.artist_id', '=', 'artists.id')
            ->where([
                ['artist_id', '=', $album->artist_id],
                ['album_id', '=', $album->id],
            ])
            ->get() as $music)
            <div class="playlist-unit">
                <a href="{{ route('musics.show',$album->id) }}">
                    <li>
                    {{ $music['name'] }} - {{ $music['pseudo'] }}
                    </li>
                </a>
            </div>
            @endforeach
        </ul>
    </div>
</div>

@endsection