sonnuage/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('playlists', 'PlaylistController');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/* Ajout de louis */
Route::get('playlists', 'PlaylistController@index')->name('playlists');

Route::get('show', 'PlaylistController@show')->name('show');

Route::get('modify', 'UserController@modify_view');

Route::post('profile', 'UserController@update_avatar');

Route::get('/admin', 'AdminController@index')->name('homeAdmin');

Route::resource('search', 'SearchController');

Route::get('/search', 'SearchController@index')->name('search');

Route::post('/search', 'SearchController@search')->name('search');

Route::resource('upload', 'UploadController');
//Route::get('/upload', 'UploadController@uploadForm')->name('upload');
//
//Route::post('/upload', 'UploadController@uploadSubmit')->name('upload');



/* Ajout de Antoine */
Route::resource('albums', 'AlbumController');

Route::get('albums', 'AlbumController@index')->name('albums');

Route::get('show', 'AlbumController@show')->name('show');

Route::resource('artists', 'ArtistController');

Route::get('artists', 'ArtistController@index')->name('artists');

Route::get('show', 'ArtistController@show')->name('show');

Route::resource('musics', 'MusicController');

Route::get('musics', 'MusicController@index')->name('musics');

Route::get('show', 'MusicController@show')->name('show');

Route::post('destroy', 'MusicController@delete')->name('delete');

sonnuage/resources/views/home.blade.php
@extends('layout')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
<div class="group-playlists">
    @foreach( $play = DB::table('playlists')->select('id', 'name', 'description')->where('owner_id', '=', (string)Auth::id())->get() as $playlists_user )
        <div class="playlist-unit">
            <img src="{{ asset('images/playlist_white.png') }}" alt="playlist" />
            <h3>{{ $playlists_user->name }}</h3>
            <p>{{ $playlists_user->description }}</p>
            <form action="{{ route('playlists.destroy',$playlists_user->id) }}" method="POST">

                <a class="btn btn-info" href="{{ route('playlists.show',$playlists_user->id) }}">Show</a>

                <a class="btn btn-primary" href="{{ route('playlists.edit',$playlists_user->id) }}">Edit</a>

                @csrf
                @method('DELETE')

                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
        </div>
    @endforeach
</div>
@endsection

sonnuage/resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>SONUAGE</title>

    <!-- Fonts -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

</head>

<body>

    <div id="parent">
        <header>
            <div class="container">
                <nav class="navbar navbar-expend-lg navbar-light">
                    <div id="logo_container">
                        <a class="navbar-brand" href="{{ url('/') }}">Sonuage
                            <img src="{{ asset('images/logo.png') }}" alt="sonuage_logo" />
                        </a>
                    </div>
                    <!-- <button class="bouton navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button> -->
                    <!-- <div class="collapse navbar-collapse" id="navbarSupportedContent"> -->
                    <div class="liste">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="lien-nav-link" href="{{ route('albums') }}">Album</a>
                            </li>
                            <li class="nav-item">
                                <a class="lien-nav-link" href="{{ route('playlists') }}">Playlist</a>
                            </li>
                            <li class="nav-item">
                                <a href="{{ route('artists') }}" class="lien-nav-link">Artiste</a>
                            </li>
                            <li class="nav-item">
                                <a href="{{ route('musics') }}" class="lien-nav-link">Musique</a>
                            </li>
                            <li class="nav-item">
                                <a href="{{ route('upload.index') }}" class="lien-nav-link btn btn-success">Upload</a>
                            </li>
                            @guest
                            <li class="nav-item">
                                <a href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                            <li class="nav-item">
                                <a href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                            @endif
                            @else
                            <li class="nav-item dropdown">
                                <div id="user-place" href="#" role="button">
                                    <div id="avatar" style="background-image: url('/storage/avatars/{{ Auth::user()->avatar }}');
                                            background-repeat: no-repeat;
                                            background-position: center;
                                            background-size: 100% 100%;
                                            ">
                                    </div>
                                </div>

                                <div class="dropdown-content" aria-labelledby="navbarDropdown">
                                    <p id="username" class="dropdown-item">
                                        {{ Auth::user()->name }}
                                    </p>
                                    <a class="dropdown-item" href="{{ url('/home') }}">
                                        Home
                                    </a>

                                    <a class="dropdown-item" href="/modify">
                                        Modify Profile
                                    </a>

                                    <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                            @endguest
                        </ul>
                    </div>
                    <!-- </div> -->
                </nav>
            </div>
        </header>
    </div>

    {{-- <div id="music-player">--}}
    {{-- <audio controls="controls">--}}
    {{-- <source src="{{ asset('storage/musics/Discovery/daft-punk-aerodynamic.mp3') }}"/>--}}
    {{-- Your browser does not support the audio element.--}}
    {{-- </audio>--}}
    {{-- </div>--}}

    <div class="content mt-4">
        @yield('content')
    </div>

    <footer>
        <p>
            Sonuage aucun droits réservés.
        </p>
        <div class="col-lg-12 margin-tb d-flex justify-content-between mb-2">
            <div id="gitlab">
                <div class="pull-left">
                    <img class="w-50" src="{{ asset('images/gitlab_black.png') }}" alt="logo de gitlab" />
                    <a href="https://gitlab.com/antoinedelbrel/projet-web" target="_blank" alt="lien vers le gitlab">Repo Gitlab</a>
                </div>
            </div>
            <div class="pull-right">
                <a href="{{ route('upload.index') }}" class="lien-nav-link btn btn-success">Upload une musique</a>
            </div>
        </div>
    </footer>
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

</body>

</html>

sonnuage/resources/views/uploadForm.blade.php
@extends('layout')

@section('content')

    <div class="container mt-4">
        <div class="col-lg-12 margin-tb d-flex justify-content-between mb-2">
            <div class="pull-left">
                <h2>Faites vibrer le monde !</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('artists') }}">Retour</a>
            </div>
        </div>

        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        @if(Session::has('success'))
            <div class="alert alert-success">
                {{ Session::get('success') }}
                @php
                    Session::forget('success');
                @endphp
            </div>
        @endif

        <form action="{{ route('upload.store') }}" method="POST" enctype="multipart/form-data">
            @csrf

            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <input type="text" name="pseudo" class="form-control" value="{{ $user->name ?? 'Anonymous User' }}" hidden>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Music name</strong>
                        <input class="form-control" name="music_name" placeholder="Music name">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Album name</strong>
                        <input class="form-control" name="album" placeholder="Album name">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group" {{ $errors->has('music_file') ? 'has-error' : '' }}>
                        <strong>Music</strong>
                        <input type="file" class="form-control" name="music_file" id="music_file">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group" {{ $errors->has('cover') ? 'has-error' : '' }}>
                        <strong>Cover</strong>
                        <input type="file" class="form-control" name="cover" id="cover">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>

        </form>
    </div>

@endsection