sonnuage/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('playlists', 'PlaylistController');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/* Ajout de louis */
Route::get('playlists', 'PlaylistController@index')->name('playlists');

Route::get('show', 'PlaylistController@show')->name('show');

Route::get('modify', 'UserController@modify_view');

Route::post('profile', 'UserController@update_avatar');

Route::get('/admin', 'AdminController@index')->name('homeAdmin');

Route::resource('search', 'SearchController');

Route::get('/search', 'SearchController@index')->name('search');

Route::post('/search', 'SearchController@search')->name('search');

Route::resource('upload', 'UploadController');
//Route::get('/upload', 'UploadController@uploadForm')->name('upload');
//
//Route::post('/upload', 'UploadController@uploadSubmit')->name('upload');



/* Ajout de Antoine */
Route::resource('albums', 'AlbumController');

Route::get('albums', 'AlbumController@index')->name('albums');

Route::get('show', 'AlbumController@show')->name('show');

Route::resource('artists', 'ArtistController');

Route::get('artists', 'ArtistController@index')->name('artists');

Route::get('show', 'ArtistController@show')->name('show');

Route::resource('musics', 'MusicController');

Route::get('musics', 'MusicController@index')->name('musics');

Route::get('show', 'MusicController@show')->name('show');

Route::post('destroy', 'MusicController@delete')->name('delete');

sonnuage/app/Playlist.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Playlist extends Model
{
    protected $fillable = [
        'name', 'description', 'music_id', 'owner_id',
    ];

    public function musics()
    {
        return $this->belongsToMany('App\Music');
    }
}

sonnuage/app/Http/Controllers/PlaylistController.php
<?php

namespace App\Http\Controllers;

use App\Playlist;
use App\Music;
use Illuminate\Http\Request;

class PlaylistController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('playlists.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('playlists.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'description' => 'required',
            'music_id' => 'required',
            'owner_id' => 'required',
        ]);
        Playlist::create($request->all());

        return redirect()
            ->route('playlists')
            ->with('success', 'Playlist created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Playlist  $playlist
     * @return \Illuminate\Http\Response
     */
    //public function show(Playlist $playlist)

    public function show(Playlist $playlist)
    {
        return view('playlists.show', compact('playlist'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Playlist  $playlist
     * @return \Illuminate\Http\Response
     */
    public function edit(Playlist $playlist)
    {
        return view('playlists.edit', compact('playlist'));
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Playlist  $playlist
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Playlist $playlist)
    {
        $request->validate([
            'name' => 'required',
            'description' => 'required',
            'music_id' => 'required',
        ]);

        $playlist->update($request->all());

        return redirect()->route('playlists')
            ->with('success', 'Playlist updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Playlist  $playlist
     * @return \Illuminate\Http\Response
     */
    public function destroy(Playlist $playlist)
    {
        $playlist->delete();

        return redirect()->route('playlists')
            ->with('success', 'Playlist deleted successfully');
    }
}

sonnuage/resources/views/playlists/create.blade.php
@extends('layout')

@section('content')

<div class="container mt-4">
    <div class="col-lg-12 margin-tb d-flex justify-content-between mb-2">
        <div class="pull-left">
            <h2>Ajoutez une nouvelle playlist</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('playlists') }}"> Retour</a>
        </div>
    </div>

    @if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <form action="{{ route('playlists.store') }}" method="POST">
        @csrf

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Description</strong>
                    <textarea class="form-control" name="description" placeholder="Description"></textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Music_id</strong>
                    <input type="text" class="form-control" name="music_id" placeholder="Music_id">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <input type="hidden" class="form-control" name="owner_id" value="{{ Auth::id() }}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
</div>

@endsection

sonnuage/resources/views/playlists/edit.blade.php
@extends('layout')

@section('content')

<div class="container mt-4">
    <div class="col-lg-12 margin-tb d-flex justify-content-between mb-2">
        <div class="pull-left">
            <h2>Modifiez la playlist</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('playlists') }}">Retour</a>
        </div>
    </div>
    @if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif
    <form action="{{ route('playlists.update',$playlist->id) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="container">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" value="{{ $playlist->name }}" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Description:</strong>
                    <input type="text" name="description" value="{{ $playlist->description }}" class="form-control" placeholder="Description">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Music id:</strong>
                    <input type="text" name="music_id" value="{{ $playlist->music_id }}" class="form-control" placeholder="music_id">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
</div>

@endsection

sonnuage/resources/views/playlists/index.blade.php
@extends('layout')

<head>
    <title>SONUAGE - Playlists</title>
</head>

@section('content')

<?php

use Illuminate\Support\Facades\DB;
$playlists = DB::table('playlists')
    ->select('playlists.id', 'playlists.name', 'playlists.description', 'playlists.owner_id', 'users.name as owner')
    ->leftJoin('users', 'playlists.owner_id', '=', 'users.id')
    ->get();
?>
<div class="container mt-4">
    <div class="col-lg-12 margin-tb d-flex justify-content-between mb-2">
        <div class="pull-left">
            <h2>Toutes les playlists</h2>
        </div>
        <div class="pull-right">
            <a href="{{ route('playlists.create') }}" class="btn btn-success">Ajoutez une nouvelle playlist</a>
        </div>
    </div>

    <div class="group-playlists">
        @foreach($playlists as $playlist)
        <div class="playlist-unit">
            <a href="{{ route('playlists.show',$playlist->id) }}">
                <img src="{{ asset('images/playlist_white.png') }}" alt="playlist" />
                <h3>{{ $playlist->name }}</h3>
                <p>{{ $playlist->description }}</p>
                <p>De <strong>{{ $playlist->owner }}</strong></p>
            </a>
        </div>
        @endforeach
    </div>
    <h2>Vos playlists</h2>
    <div class="group-playlists">
        @foreach( $play = DB::table('playlists')->select('id', 'name', 'description')->where('owner_id', '=', (string)Auth::id())->get() as $playlists_user )
        <div class="playlist-unit">
            <img src="{{ asset('images/playlist_white.png') }}" alt="playlist" />
            <h3>{{ $playlists_user->name }}</h3>
            <p>{{ $playlists_user->description }}</p>
            <form action="{{ route('playlists.destroy',$playlists_user->id) }}" method="POST">

                <a class="btn btn-info" href="{{ route('playlists.show',$playlists_user->id) }}">Show</a>

                <a class="btn btn-primary" href="{{ route('playlists.edit',$playlists_user->id) }}">Edit</a>

                @csrf
                @method('DELETE')

                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
        </div>
        @endforeach
    </div>
</div>
@endsection

sonnuage/resources/views/playlists/show.blade.php
<?php

use Illuminate\Support\Facades\DB; ?>
@extends('layout')

@section('content')

<?php
$playlists = DB::table('playlists')
    ->select('playlists.id', 'playlists.name as playlist_name', 'playlists.description', 'playlists.owner_id', 'users.name as owner', 'musics.name as music_name')
    ->leftJoin('users', 'playlists.owner_id', '=', 'users.id')
    ->leftJoin('musics', 'users.id', '=', 'musics.artist_id')
    ->where('playlists.id', '=', $playlist->id)
    ->first();
?>
<div class="container mt-4">
    <div class="col-lg-12 margin-tb d-flex justify-content-between mb-2">
        <div class="pull-left">
            <h2>Votre Playlist</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('playlists') }}">Retour</a>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $playlists->playlist_name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Owner:</strong>
                {{ $playlists->owner }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Description:</strong>
                {{ $playlists->description }}
            </div>
        </div>
        <?php
        $musics = DB::table('playlists')
            ->select('musics.name as music_name', 'musics.id as music_id')
            ->leftJoin('musics', 'playlists.music_id', '=', 'musics.id')
            ->where('playlists.id', '=', $playlist->id)
            ->get();
        ?>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <h3>Musics :</h3>
                @foreach($musics as $music)
                <a href="{{ route('musics.show', $music->music_id) }}">
                    <p>-> {{ $music->music_name }}</p>
                </a>
                @endforeach
            </div>
        </div>

    </div>

    @endsection