sonnuage/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('playlists', 'PlaylistController');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/* Ajout de louis */
Route::get('playlists', 'PlaylistController@index')->name('playlists');

Route::get('show', 'PlaylistController@show')->name('show');

Route::get('modify', 'UserController@modify_view');

Route::post('profile', 'UserController@update_avatar');

Route::get('/admin', 'AdminController@index')->name('homeAdmin');

Route::resource('search', 'SearchController');

Route::get('/search', 'SearchController@index')->name('search');

Route::post('/search', 'SearchController@search')->name('search');

Route::resource('upload', 'UploadController');
//Route::get('/upload', 'UploadController@uploadForm')->name('upload');
//
//Route::post('/upload', 'UploadController@uploadSubmit')->name('upload');



/* Ajout de Antoine */
Route::resource('albums', 'AlbumController');

Route::get('albums', 'AlbumController@index')->name('albums');

Route::get('show', 'AlbumController@show')->name('show');

Route::resource('artists', 'ArtistController');

Route::get('artists', 'ArtistController@index')->name('artists');

Route::get('show', 'ArtistController@show')->name('show');

Route::resource('musics', 'MusicController');

Route::get('musics', 'MusicController@index')->name('musics');

Route::get('show', 'MusicController@show')->name('show');

Route::post('destroy', 'MusicController@delete')->name('delete');

sonnuage/app/Artist.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Permission\Traits\HasRoles;

class Artist extends Model
{
    use HasRoles;

    protected $fillable = [
        'pseudo', 'user_id'
    ];

    public function musics()
    {
        return $this->belongsToMany('App\Music');
    }

    public function albums()
    {
        return $this->hasMany('App\Album');
    }

    public function user(){
        return $this->belongsTo('App\User');
    }
}

sonnuage/app/Http/Controllers/ArtistController.php
<?php

namespace App\Http\Controllers;

use App\Artist;
use App\Music;
use App\Album;
use Illuminate\Http\Request;

class ArtistController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('artists.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Music  $artist
     * @return \Illuminate\Http\Response
     */
    //public function show(Artist $music)

    public function show(Artist $artist)
    {
        return view('artists.show', compact('artist'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Artist  $artist
     * @return \Illuminate\Http\Response
     */
    public function destroy(Artist $artist)
    {
        $artist->delete();

        return redirect()->route('artists')
            ->with('success', 'Artist deleted successfully');
    }
}

sonnuage/resources/views/artists/index.blade.php
@extends('layout')

@section('content')
<div class="container">
    <div class="col-lg-12 margin-tb d-flex justify-content-between mb-2">
        <div class="pull-left">
            <h2>Tous les Artistes</h2>
        </div>
    </div>

    <?php
    use Illuminate\Support\Facades\DB;
    $artists = DB::table('artists')->select('id', 'pseudo', 'user_id')->get();
    ?>

    <div class="group-playlists">
        @foreach($artists as $artist)
            <?php
            $user = DB::table('users')
                ->select('artists.id', 'users.avatar')
                ->leftJoin('artists', 'artists.user_id', '=', 'users.id')
                ->where('users.id', '=', $artist->user_id)
                ->first();
            ?>
            <div class="playlist-unit">
                <a href="{{ route('artists.show',$artist->id) }}">
                    <img src="/storage/avatars/{{ $user->avatar }}" alt="{{ $artist->pseudo }} picture" />
                    <h3>{{ $artist->pseudo }}</h3>
                </a>
            </div>
        @endforeach
    </div>
</div>
@endsection

sonnuage/resources/views/artists/show.blade.php
@extends('layout')

@section('content')
    <?php
    use Illuminate\Support\Facades\DB;
    $user = DB::table('users')
        ->select('users.id', 'artists.id', 'users.avatar')
        ->leftJoin('artists', 'artists.user_id', '=', 'users.id')
        ->where('users.id', '=', $artist->user_id)
        ->first();

    $albums = DB::table('albums')
        ->select('id', 'artist_id', 'title', 'release_date')
        ->where('artist_id', '=', $user->id)
        ->get();
    ?>
    <div class="container">
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('artists') }}">Retour</a>
        </div>
        <div id="user_baniere">
            <div id="image">
                <img src="/storage/avatars/{{ $user->avatar }}" alt="{{ $artist->pseudo }} picture" />
            </div>
            <div class="text">
                <h2>{{ $artist->pseudo }}</h2>
            </div>
        </div>
        <div id="albums-list">
            <div class="text">
                <h3>Albums :</h3>
            </div>
            <ul>
                @foreach($albums as $album)
                    <li>
                        <a href="{{ route('albums.show', $album->id) }}">
                        {{ $album->title }}
                        </a>
                    </li>
                @endforeach
            </ul>
        </div>
    </div>
@endsection